baseURL = "https://koman.app/"
locale = "en-us"
title = "Koman"

[params]
  owner = "Koman"
  intro = "I'm a composer and music producer working in media with a parallel interest in software engineering."
  description = "Audio focused utility apps"
